### ISSUE TITLE
fiskaly-kassensichv-client package does not exist on NPMJS repo

### ISSUE THREAD

**Issue by christxph** [fiskaly/fiskaly-kassensichv-client-node#9]
The command 

```
npm install fiskaly-kassensichv-client
```

fails because fiskaly-kassensichv-client is not published on npmjs.com

Could you please publish the package so that it can be installed using the command in the README.md?

Thanks!

**Comment by prempador** [comment]
Thank you @christxph for your Bug Report. Development of this project was halted. We are currently working on a successor and will add the new package to npm as soon as it is live.
